name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements_mini.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_mini.txt

    - name: Run basic training test
      run: |
        python training.py --dataset_name pathmnist --image_size 28 --disable_mlflow --save_model --smoke_test

    - name: Run evaluation test
      run: |
        python test.py --checkpoint_path outputs/latest/model --dataset_name pathmnist --image_size 28 --smoke_test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: training-outputs
        path: |
          outputs/latest/artifacts/generated_samples.png
          outputs/latest/artifacts/losses_train.png
        if-no-files-found: warn

    - name: Clean up
      run: |
        rm -rf outputs/latest/model
        rm -rf ~/.cache/pip
